import {
  BatchDownload,
  CalculateChecksum,
  CheckEnvironment,
  ClearHistory,
  DecryptData,
  DownloadFile,
  EncryptData,
  GenerateDownloadLink,
  GenerateEncryptionKey,
  GetAvailableFiles,
  GetDownloadInfo,
  GetHistory,
  GetPerformanceStats,
  GetServerInfo,
  GetUserConfig,
  InitThreadPool,
  ResetUserConfig,
  SaveUserConfig,
  SelectFiles,
  StopThreadPool,
  VerifyFile
} from '../../wailsjs/go/app/App'

export default {
  GetServerInfo,
  SelectFiles,
  GenerateDownloadLink,
  GetAvailableFiles,
  GetDownloadInfo,
  DownloadFile,
  BatchDownload,
  CalculateChecksum,
  VerifyFile,
  EncryptData,
  DecryptData,
  GenerateEncryptionKey,
  GetPerformanceStats,
  InitThreadPool,
  StopThreadPool,
  CheckEnvironment,
  GetUserConfig,
  SaveUserConfig,
  ResetUserConfig,
  GetHistory,
  ClearHistory,
}
