// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownload(arg1, arg2) {
  return window['go']['app']['App']['BatchDownload'](arg1, arg2);
}

export function CalculateChecksum(arg1) {
  return window['go']['app']['App']['CalculateChecksum'](arg1);
}

export function CheckEnvironment() {
  return window['go']['app']['App']['CheckEnvironment']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function DecryptData(arg1, arg2) {
  return window['go']['app']['App']['DecryptData'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2);
}

export function EncryptData(arg1, arg2) {
  return window['go']['app']['App']['EncryptData'](arg1, arg2);
}

export function GenerateDownloadLink(arg1) {
  return window['go']['app']['App']['GenerateDownloadLink'](arg1);
}

export function GenerateEncryptionKey() {
  return window['go']['app']['App']['GenerateEncryptionKey']();
}

export function GetAvailableFiles() {
  return window['go']['app']['App']['GetAvailableFiles']();
}

export function GetDownloadInfo(arg1) {
  return window['go']['app']['App']['GetDownloadInfo'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetPerformanceStats() {
  return window['go']['app']['App']['GetPerformanceStats']();
}

export function GetServerInfo() {
  return window['go']['app']['App']['GetServerInfo']();
}

export function GetUserConfig() {
  return window['go']['app']['App']['GetUserConfig']();
}

export function InitThreadPool(arg1) {
  return window['go']['app']['App']['InitThreadPool'](arg1);
}

export function ResetUserConfig() {
  return window['go']['app']['App']['ResetUserConfig']();
}

export function SaveUserConfig(arg1) {
  return window['go']['app']['App']['SaveUserConfig'](arg1);
}

export function SelectFiles(arg1) {
  return window['go']['app']['App']['SelectFiles'](arg1);
}

export function StopThreadPool() {
  return window['go']['app']['App']['StopThreadPool']();
}

export function VerifyFile(arg1, arg2) {
  return window['go']['app']['App']['VerifyFile'](arg1, arg2);
}
