// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownload(arg1, arg2) {
  return window['go']['app']['App']['BatchDownload'](arg1, arg2);
}

export function CalculateChecksum(arg1) {
  return window['go']['app']['App']['CalculateChecksum'](arg1);
}

export function CheckEnvironment() {
  return window['go']['app']['App']['CheckEnvironment']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function DecryptData(arg1, arg2) {
  return window['go']['app']['App']['DecryptData'](arg1, arg2);
}

export function DeleteHistory(arg1) {
  return window['go']['app']['App']['DeleteHistory'](arg1);
}

export function DiscoverPeers() {
  return window['go']['app']['App']['DiscoverPeers']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2);
}

export function EncryptData(arg1, arg2) {
  return window['go']['app']['App']['EncryptData'](arg1, arg2);
}

export function GenerateBatchDownloadLink(arg1) {
  return window['go']['app']['App']['GenerateBatchDownloadLink'](arg1);
}

export function GenerateDownloadLink(arg1) {
  return window['go']['app']['App']['GenerateDownloadLink'](arg1);
}

export function GenerateDownloadLinkForFile(arg1) {
  return window['go']['app']['App']['GenerateDownloadLinkForFile'](arg1);
}

export function GenerateEncryptionKey() {
  return window['go']['app']['App']['GenerateEncryptionKey']();
}

export function GetAllIPs() {
  return window['go']['app']['App']['GetAllIPs']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAvailableFiles() {
  return window['go']['app']['App']['GetAvailableFiles']();
}

export function GetDownloadInfo(arg1) {
  return window['go']['app']['App']['GetDownloadInfo'](arg1);
}

export function GetDownloadInfoWithKey(arg1, arg2) {
  return window['go']['app']['App']['GetDownloadInfoWithKey'](arg1, arg2);
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetPerformanceStats() {
  return window['go']['app']['App']['GetPerformanceStats']();
}

export function GetProtocolRecommendation(arg1) {
  return window['go']['app']['App']['GetProtocolRecommendation'](arg1);
}

export function GetProtocolStatus() {
  return window['go']['app']['App']['GetProtocolStatus']();
}

export function GetSecurityInfo() {
  return window['go']['app']['App']['GetSecurityInfo']();
}

export function GetSelectedIP() {
  return window['go']['app']['App']['GetSelectedIP']();
}

export function GetServerInfo() {
  return window['go']['app']['App']['GetServerInfo']();
}

export function GetUserConfig() {
  return window['go']['app']['App']['GetUserConfig']();
}

export function InitThreadPool(arg1) {
  return window['go']['app']['App']['InitThreadPool'](arg1);
}

export function LogDebug(arg1) {
  return window['go']['app']['App']['LogDebug'](arg1);
}

export function LogError(arg1) {
  return window['go']['app']['App']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['app']['App']['LogInfo'](arg1);
}

export function LogWarn(arg1) {
  return window['go']['app']['App']['LogWarn'](arg1);
}

export function ParseEncryptedToken(arg1, arg2) {
  return window['go']['app']['App']['ParseEncryptedToken'](arg1, arg2);
}

export function ReadTextFile(arg1) {
  return window['go']['app']['App']['ReadTextFile'](arg1);
}

export function RegenerateLink(arg1) {
  return window['go']['app']['App']['RegenerateLink'](arg1);
}

export function ResetUserConfig() {
  return window['go']['app']['App']['ResetUserConfig']();
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['app']['App']['SaveTextFile'](arg1, arg2);
}

export function SaveUserConfig(arg1) {
  return window['go']['app']['App']['SaveUserConfig'](arg1);
}

export function SelectFiles(arg1) {
  return window['go']['app']['App']['SelectFiles'](arg1);
}

export function SelectProtocol(arg1, arg2, arg3) {
  return window['go']['app']['App']['SelectProtocol'](arg1, arg2, arg3);
}

export function SelectSaveFile(arg1) {
  return window['go']['app']['App']['SelectSaveFile'](arg1);
}

export function SetManualIP(arg1) {
  return window['go']['app']['App']['SetManualIP'](arg1);
}

export function SetProtocolPreference(arg1) {
  return window['go']['app']['App']['SetProtocolPreference'](arg1);
}

export function SetSelectedIP(arg1) {
  return window['go']['app']['App']['SetSelectedIP'](arg1);
}

export function StopThreadPool() {
  return window['go']['app']['App']['StopThreadPool']();
}

export function VerifyFile(arg1, arg2) {
  return window['go']['app']['App']['VerifyFile'](arg1, arg2);
}
