// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownload(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function CalculateChecksum(arg1:string):Promise<string>;

export function CheckEnvironment():Promise<Record<string, any>>;

export function ClearHistory():Promise<void>;

export function DecryptData(arg1:string,arg2:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function EncryptData(arg1:string,arg2:string):Promise<string>;

export function GenerateDownloadLink(arg1:string):Promise<Record<string, any>>;

export function GenerateEncryptionKey():Promise<string>;

export function GetAvailableFiles():Promise<Array<Record<string, any>>>;

export function GetDownloadInfo(arg1:string):Promise<Record<string, any>>;

export function GetHistory(arg1:number):Promise<Array<Record<string, any>>>;

export function GetPerformanceStats():Promise<Record<string, any>>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetUserConfig():Promise<Record<string, any>>;

export function InitThreadPool(arg1:number):Promise<void>;

export function ResetUserConfig():Promise<void>;

export function SaveUserConfig(arg1:Record<string, any>):Promise<void>;

export function SelectFiles(arg1:boolean):Promise<Array<Record<string, any>>>;

export function StopThreadPool():Promise<void>;

export function VerifyFile(arg1:string,arg2:string):Promise<boolean>;
