// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownload(arg1:Array<string>,arg2:string):Promise<Record<string, any>>;

export function CalculateChecksum(arg1:string):Promise<string>;

export function CheckEnvironment():Promise<Record<string, any>>;

export function ClearHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function DecryptData(arg1:string,arg2:string):Promise<string>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DiscoverPeers():Promise<Array<Record<string, any>>>;

export function DownloadFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function EncryptData(arg1:string,arg2:string):Promise<string>;

export function GenerateBatchDownloadLink(arg1:Array<string>):Promise<Record<string, any>>;

export function GenerateDownloadLink(arg1:string):Promise<Record<string, any>>;

export function GenerateDownloadLinkForFile(arg1:string):Promise<Record<string, any>>;

export function GenerateEncryptionKey():Promise<string>;

export function GetAllIPs():Promise<Array<Record<string, any>>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetAvailableFiles():Promise<Array<Record<string, any>>>;

export function GetDownloadInfo(arg1:string):Promise<Record<string, any>>;

export function GetDownloadInfoWithKey(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetHistory(arg1:number):Promise<Array<Record<string, any>>>;

export function GetLogs():Promise<Array<Record<string, any>>>;

export function GetPerformanceStats():Promise<Record<string, any>>;

export function GetProtocolRecommendation(arg1:number):Promise<Record<string, any>>;

export function GetProtocolStatus():Promise<Record<string, any>>;

export function GetSecurityInfo():Promise<Record<string, any>>;

export function GetSelectedIP():Promise<string>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetUserConfig():Promise<Record<string, any>>;

export function InitThreadPool(arg1:number):Promise<void>;

export function LogDebug(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function LogWarn(arg1:string):Promise<void>;

export function ParseEncryptedToken(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RegenerateLink(arg1:number):Promise<Record<string, any>>;

export function ResetUserConfig():Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SaveUserConfig(arg1:Record<string, any>):Promise<void>;

export function SelectFiles(arg1:boolean):Promise<Array<Record<string, any>>>;

export function SelectProtocol(arg1:number,arg2:boolean,arg3:string):Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SetManualIP(arg1:string):Promise<void>;

export function SetProtocolPreference(arg1:string):Promise<void>;

export function SetSelectedIP(arg1:string):Promise<void>;

export function StopThreadPool():Promise<void>;

export function VerifyFile(arg1:string,arg2:string):Promise<boolean>;
